//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_SEGUROS_CLIENT.ServiceTareas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarea", Namespace="http://schemas.datacontract.org/2004/07/WS_SEGUROS")]
    [System.SerializableAttribute()]
    public partial class Tarea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompletadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Completada {
            get {
                return this.CompletadaField;
            }
            set {
                if ((object.ReferenceEquals(this.CompletadaField, value) != true)) {
                    this.CompletadaField = value;
                    this.RaisePropertyChanged("Completada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTareas.IServiceTareas")]
    public interface IServiceTareas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/GetTareas", ReplyAction="http://tempuri.org/IServiceTareas/GetTareasResponse")]
        System.Data.DataSet GetTareas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/GetTareas", ReplyAction="http://tempuri.org/IServiceTareas/GetTareasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTareasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/GetByIdTareas", ReplyAction="http://tempuri.org/IServiceTareas/GetByIdTareasResponse")]
        System.Data.DataSet GetByIdTareas(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/GetByIdTareas", ReplyAction="http://tempuri.org/IServiceTareas/GetByIdTareasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetByIdTareasAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/InsertTarea", ReplyAction="http://tempuri.org/IServiceTareas/InsertTareaResponse")]
        string InsertTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/InsertTarea", ReplyAction="http://tempuri.org/IServiceTareas/InsertTareaResponse")]
        System.Threading.Tasks.Task<string> InsertTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/UpdateTarea", ReplyAction="http://tempuri.org/IServiceTareas/UpdateTareaResponse")]
        string UpdateTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/UpdateTarea", ReplyAction="http://tempuri.org/IServiceTareas/UpdateTareaResponse")]
        System.Threading.Tasks.Task<string> UpdateTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/DeleteTarea", ReplyAction="http://tempuri.org/IServiceTareas/DeleteTareaResponse")]
        bool DeleteTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTareas/DeleteTarea", ReplyAction="http://tempuri.org/IServiceTareas/DeleteTareaResponse")]
        System.Threading.Tasks.Task<bool> DeleteTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTareasChannel : WS_SEGUROS_CLIENT.ServiceTareas.IServiceTareas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTareasClient : System.ServiceModel.ClientBase<WS_SEGUROS_CLIENT.ServiceTareas.IServiceTareas>, WS_SEGUROS_CLIENT.ServiceTareas.IServiceTareas {
        
        public ServiceTareasClient() {
        }
        
        public ServiceTareasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTareasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTareasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTareasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTareas() {
            return base.Channel.GetTareas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTareasAsync() {
            return base.Channel.GetTareasAsync();
        }
        
        public System.Data.DataSet GetByIdTareas(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.GetByIdTareas(tarea);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetByIdTareasAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.GetByIdTareasAsync(tarea);
        }
        
        public string InsertTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.InsertTarea(tarea);
        }
        
        public System.Threading.Tasks.Task<string> InsertTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.InsertTareaAsync(tarea);
        }
        
        public string UpdateTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.UpdateTarea(tarea);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.UpdateTareaAsync(tarea);
        }
        
        public bool DeleteTarea(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.DeleteTarea(tarea);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTareaAsync(WS_SEGUROS_CLIENT.ServiceTareas.Tarea tarea) {
            return base.Channel.DeleteTareaAsync(tarea);
        }
    }
}
